version: '3'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               python manage.py crawling &&
               python manage.py seed_games SteamGamesDataset/steam_games_dataset.csv &&
               python manage.py seed_interest &&
               python manage.py steam_data &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  media_volume: