# Generated by Django 4.2.13 on 2025-01-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_adult",
            field=models.BooleanField(default=False),
        ),
    ]
