# Generated by Django 4.2 on 2025-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_tag_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ko',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
