# Generated by Django 4.2 on 2025-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tag_name_en_alter_tag_name_ko'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_steam',
            field=models.BooleanField(default=False),
        ),
    ]
