# Generated by Django 4.2 on 2025-01-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interest_tag_account_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='steam_tag_id',
            field=models.IntegerField(default=0),
        ),
    ]
