# Generated by Django 4.2 on 2025-01-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_steam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_steam',
        ),
        migrations.AddField(
            model_name='account',
            name='steamId',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
