# Generated by Django 4.2.13 on 2025-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
